/*
 * 
 * Modified class files generated by swagger code generation from
 * 
 * RSpace Inventory API
 * Welcome to the RSpace Inventory API.  | Api version | Required minimum RSpace version| | --- | --- | | 1.7.0 | 1.70 | | 1.7.1 | 1.71 | 
 *
 * OpenAPI spec version: 1.7.1
 * Contact: support@researchspace.com
 *
 */



package com.researchspace.samples.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A metadata link.
 */
@ApiModel(description = "A metadata link.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-10-23T10:46:11.180Z")
public class LinkItem {
  @SerializedName("link")
  private String link = null;

  @SerializedName("rel")
  private String rel = null;

  public LinkItem link(String link) {
    this.link = link;
    return this;
  }

   /**
   * URL.
   * @return link
  **/
  @ApiModelProperty(value = "URL.")
  public String getLink() {
    return link;
  }

  public void setLink(String link) {
    this.link = link;
  }

  public LinkItem rel(String rel) {
    this.rel = rel;
    return this;
  }

   /**
   * The relation, an IANA registered relation type as listed https://www.iana.org/assignments/link-relations/link-relations.xml 
   * @return rel
  **/
  @ApiModelProperty(value = "The relation, an IANA registered relation type as listed https://www.iana.org/assignments/link-relations/link-relations.xml ")
  public String getRel() {
    return rel;
  }

  public void setRel(String rel) {
    this.rel = rel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkItem linkItem = (LinkItem) o;
    return Objects.equals(this.link, linkItem.link) &&
        Objects.equals(this.rel, linkItem.rel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, rel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkItem {\n");
    
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    rel: ").append(toIndentedString(rel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

